# главные настройки
[alembic]
# путь к папке с файлами миграци
script_location = %(here)s/alembic
# добавление текущей папки в пути импорта
prepend_sys_path = .
path_separator = os
# строка подключения Alembic к бд PostgreSQL
sqlalchemy.url = postgresql+psycopg2://anna@localhost:5432/Culinary_news_portal

# настройка пост-обработчиков
[post_write_hooks]

# настройка списка логгеров, используемых в проекте
[loggers]
keys = root,sqlalchemy,alembic

# куда отправлять логи
[handlers]
keys = console

# визуальное оформление логов
[formatters]
keys = generic

# корневой логгер
[logger_root]
level = WARNING
handlers = console
qualname =

# логгер SQLAlchemy для отслеживания работы движка и SQL-запросов
[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

# логгер Alembic для вывода информации о миграциях
[logger_alembic]
level = INFO
handlers =
qualname = alembic

# настройка консольного обработчика
[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S